# Generated by Django 5.1.7 on 2025-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
